name: ci
on:
  push:
    branches: [master]
    tags: ["v*"]
    paths-ignore: ['**.md']
  pull_request:
    types: [opened, synchronize]
    paths-ignore: ['**.md']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      # ref: https://text.superbrothers.dev/200510-ensure-go-mod-is-already-tidied-on-ci/
      - name: Ensure go.mod is already tidied
        run: go mod tidy && git diff -s --exit-code go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.35
      - name: test
        run: go test -v ./...
